on:
    push:
        branches: ["main"]
jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4.2.1
            - name: Deloy as user
              run: bash -leo
            - name: Install dependencies
              run: deno install
            - run: |
                  touch .env
                  echo "${{ secrets.ENV }}" >> .env
            - name: Run deloy script
              run: deno task deloy
            - name: Stop all proccesses
              run: pm2 delete all || true
            - name: Start a new process
              run: pm2 start "deno task start"
