on:
  push: 
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4.2.0
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.4
      with:
        node-version: 20.x
    - run: bun install
    - run: |
        touch .env
        echo "${{ secrets.ENV }}" >> .env
    - run: bun start &
    
