on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: self-hosted

        steps:
            - run: echo PATH=$PATH >> /runnertmp/.env
            - run: deno install
            - run: |
                  touch .env
                  echo "${{ secrets.ENV }}" >> .env
            - name: Stop all proccess
              run: pm2 delete all || true
            - name: Start a new process
              run: pm2 start "deno -A src/index.ts"
