on:
  push: 
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4.2.0
    - run: bun install
    - run: |
        touch .env
        echo "${{ secrets.ENV }}" >> .env
    - name: Stop all proccess
      run: pm2 stop all || true
    - name: Start a new process
      run: pm2 start --interpreter ~/.bun/bin/bun src/index.ts
    
